//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLTE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class peserta_profil
    {
        public long id { get; set; }
        public string create_by { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string keterangan { get; set; }
        public string status { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string alamat_peserta { get; set; }
        public string nama_foto { get; set; }
        public string nama_peserta { get; set; }
        public string no_telp { get; set; }
        public string tanggal_lahir { get; set; }
        public string tempat_lahir { get; set; }
        public Nullable<long> peserta_id { get; set; }
    
        public virtual peserta peserta { get; set; }
    }
}
