//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PesertaNET.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TesttimemeEntities : DbContext
    {
        public TesttimemeEntities()
            : base("name=TesttimemeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<admin> admin { get; set; }
        public DbSet<peserta> peserta { get; set; }
        public DbSet<peserta_jawaban_detail> peserta_jawaban_detail { get; set; }
        public DbSet<peserta_profil> peserta_profil { get; set; }
        public DbSet<peserta_test> peserta_test { get; set; }
        public DbSet<soal> soal { get; set; }
        public DbSet<soal_kelompok> soal_kelompok { get; set; }
        public DbSet<soal_pilihan_jawaban> soal_pilihan_jawaban { get; set; }
        public DbSet<soal_type> soal_type { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<test> test { get; set; }
        public DbSet<test_sub> test_sub { get; set; }
        public DbSet<test_sub_soal> test_sub_soal { get; set; }
    }
}
