//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PesertaNET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class soal
    {
        public soal()
        {
            this.peserta_jawaban_detail = new HashSet<peserta_jawaban_detail>();
            this.test_sub_soal = new HashSet<test_sub_soal>();
            this.soal_pilihan_jawaban = new HashSet<soal_pilihan_jawaban>();
        }
    
        public long id { get; set; }
        public string create_by { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string keterangan { get; set; }
        public string status { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public int nilai_soal { get; set; }
        public string isi_soal { get; set; }
        public Nullable<long> soal_kelompok_id { get; set; }
        public Nullable<long> soal_type_id { get; set; }
    
        public virtual ICollection<peserta_jawaban_detail> peserta_jawaban_detail { get; set; }
        public virtual soal_type soal_type { get; set; }
        public virtual soal_kelompok soal_kelompok { get; set; }
        public virtual ICollection<test_sub_soal> test_sub_soal { get; set; }
        public virtual ICollection<soal_pilihan_jawaban> soal_pilihan_jawaban { get; set; }
    }
}
