//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Test_OnlineEntities : DbContext
    {
        public Test_OnlineEntities()
            : base("name=Test_OnlineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<KELOMPOK_SOAL> KELOMPOK_SOAL { get; set; }
        public DbSet<PESERTA> PESERTA { get; set; }
        public DbSet<PESERTA_JAWABAN_DETAIL> PESERTA_JAWABAN_DETAIL { get; set; }
        public DbSet<PESERTA_TES> PESERTA_TES { get; set; }
        public DbSet<PILIHAN_JAWABAN> PILIHAN_JAWABAN { get; set; }
        public DbSet<PROFIL_PESERTA> PROFIL_PESERTA { get; set; }
        public DbSet<SOAL> SOAL { get; set; }
        public DbSet<SUBTES> SUBTES { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TES> TES { get; set; }
        public DbSet<TIPE_SOAL> TIPE_SOAL { get; set; }
        public DbSet<WILAYAH> WILAYAH { get; set; }
    }
}
