//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PESERTA_TES
    {
        public PESERTA_TES()
        {
            this.PESERTA_JAWABAN_DETAIL = new HashSet<PESERTA_JAWABAN_DETAIL>();
        }
    
        public int ID_PESERTA_TEST { get; set; }
        public Nullable<int> ID_PESERTA { get; set; }
        public Nullable<int> ID_TES { get; set; }
        public Nullable<System.DateTime> TGL_TES { get; set; }
        public string Created_by { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public string Modified_by { get; set; }
    
        public virtual PESERTA PESERTA { get; set; }
        public virtual ICollection<PESERTA_JAWABAN_DETAIL> PESERTA_JAWABAN_DETAIL { get; set; }
        public virtual TES TES { get; set; }
    }
}
