//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PESERTA
    {
        public PESERTA()
        {
            this.PESERTA_TES = new HashSet<PESERTA_TES>();
        }
    
        public int ID_PESERTA { get; set; }
        public Nullable<int> ID_PROFIL { get; set; }
        public string EMAIL { get; set; }
        public string PASSWORD { get; set; }
        public string Created_by { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public string Modified_by { get; set; }
        public Nullable<bool> Is_Active { get; set; }
    
        public virtual ICollection<PESERTA_TES> PESERTA_TES { get; set; }
        public virtual PROFIL_PESERTA PROFIL_PESERTA { get; set; }
    }
}
