//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBTES
    {
        public SUBTES()
        {
            this.SOAL = new HashSet<SOAL>();
        }
    
        public int ID_SUBTES { get; set; }
        public Nullable<int> ID_TES { get; set; }
        public Nullable<System.DateTime> DURASI_SUB { get; set; }
        public string Created_by { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public string Modified_by { get; set; }
        public Nullable<bool> Is_Active { get; set; }
    
        public virtual TES TES { get; set; }
        public virtual ICollection<SOAL> SOAL { get; set; }
    }
}
