//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TES
    {
        public TES()
        {
            this.PESERTA_TES = new HashSet<PESERTA_TES>();
            this.SUBTES = new HashSet<SUBTES>();
        }
    
        public int ID_TES { get; set; }
        public string Created_by { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public string Modified_by { get; set; }
    
        public virtual ICollection<PESERTA_TES> PESERTA_TES { get; set; }
        public virtual ICollection<SUBTES> SUBTES { get; set; }
    }
}
