//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BukuResult.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class buku
    {
        public buku()
        {
            this.detailPinjam = new HashSet<detailPinjam>();
        }
    
        public int id { get; set; }
        public string judul { get; set; }
        public int stok { get; set; }
    
        public virtual ICollection<detailPinjam> detailPinjam { get; set; }
    }
}
