//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BukuResult.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detailPinjam
    {
        public int id { get; set; }
        public Nullable<int> buku_id { get; set; }
        public Nullable<int> notaPinjam_id { get; set; }
        public System.DateTime tanggalKembali { get; set; }
    
        public virtual buku buku { get; set; }
        public virtual notaPinjam notaPinjam { get; set; }
    }
}
